### ISSUE TITLE
call NeqSim API from Matlab

### ISSUE THREAD

**Issue by EvenSol** [equinor/neqsimmatlab#40]
@asmfstatoil  
Could calls to the NeqSim Live API be done from matlab (as we can do from ths example in python):
https://github.com/equinor/NeqSimLive/blob/main/JSV/example/testPROrestAPI.ipynb

**Comment by asmfstatoil** [comment]
Check out branch testRest. I have not been able to authenticate, but webwrite is the native way to run post towards a restapi. The reason it does not work for me yet is probably because I did not find the correct key, but could also be a keyname issue... You need to try some variations based on your working version of the jupyter workbook

**Comment by EvenSol** [comment]
Thanks - I made an addition of a header to the weboptions, and now it works :-)
